### PR TITLE
Make the describetable command do \df+ for functions

### PR DESCRIPTION
**Pull request by koljonen**
Just assume it's a function if the character after it is an opening parenthesis.

### CODE REVIEW

**Comment by darikg** [comment]
So if I do:
`select * from generate_series(|` 

(Where the pipe `|` means the cursor position) and hit F1, I get `invalid regular expression: parentheses () not balanced`

With `select * from generate_series(|)` , it's `Did not find any relation named ().`

I guess it has to be `select * from generate_series|(`?

**Comment by koljonen** [comment]
I added some code to handle cases where the parentheses are part of the selection or the cursor is after the opening parenthesis.

**Comment by darikg** [comment]
One last quirk... there's still a problem if the function is inside of a schema.

```
create schema temp;
create function temp.testfunc() returns int language sql as $$ select 1; $$;
```

then `select * from temp.testfunc(|` calls `\df+ testfunc` instead of `\df+ temp.testfunc`

**Comment by darikg** [comment]
Awesome, thanks for handling all the edge cases.

**Pull request merged**
